language: python
python:
  - "2.7"
  - "3.5"
services:
  - redis
addons:
  mariadb: '10.0'
install:
  - "pip install -e ."
  - "pip install -r requirements.txt"
before_script:
  - mysql -e 'create database wallstreet_test;'
  - "echo {\\\"edgar\\\": {\\\"core_key\\\":\\\"$EDGARCOREKEY\\\"}} > config_local.json"
script:
  - py.test